services:
  tempo:
    build: ./
    ports:
      - "[::1]:3200:3200" # Tempo HTTP server
      - "4317:4317" # OTLP gRPC (not used here, but available)
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    environment:
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION: ${S3_REGION}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
